# Generated by Django 5.0.6 on 2024-06-19 17:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('link', models.CharField(max_length=255)),
                ('max_width', models.FloatField(blank=True)),
                ('max_height', models.FloatField(blank=True)),
                ('vertical_mirror', models.BooleanField(default=False)),
                ('horizontal_mirror', models.BooleanField(default=False)),
                ('max_stitch_width', models.FloatField(blank=True)),
                ('max_stitch_height', models.FloatField(blank=True)),
                ('text_position', models.PositiveIntegerField(choices=[])),
                ('is_superimposed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_width', models.IntegerField()),
                ('container_height', models.IntegerField()),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.element')),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.type'),
        ),
    ]
