# Generated by Django 5.0.6 on 2024-07-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='max_stitch_height',
            new_name='min_stitch_width',
        ),
    ]
