# Generated by Django 5.0.6 on 2024-06-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='max_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='max_stitch_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='max_stitch_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='max_width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
