# Generated by Django 5.0.6 on 2024-07-19 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_rename_max_stitch_height_element_min_stitch_width'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='link',
            new_name='local_link',
        ),
    ]
