# Generated by Django 5.0.6 on 2024-06-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_alter_element_max_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='text_position',
            field=models.PositiveIntegerField(choices=[(1, 'BOTTOM'), (2, 'RIGHT'), (3, 'LEFT'), (4, 'CENTER'), (5, 'CENTER')]),
        ),
    ]
