# Generated by Django 5.0.6 on 2024-07-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_alter_element_text_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='text_position',
            field=models.PositiveIntegerField(choices=[(1, 'BOTTOM'), (2, 'RIGHT'), (3, 'LEFT'), (4, 'CENTER'), (5, 'TOP')]),
        ),
    ]
