# Generated by Django 5.0.6 on 2024-07-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_rename_link_element_local_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
