# Generated by Django 5.0.6 on 2024-07-08 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0004_alter_element_text_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='type',
        ),
        migrations.RemoveField(
            model_name='trainingdata',
            name='element',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.DeleteModel(
            name='Element',
        ),
        migrations.DeleteModel(
            name='TrainingData',
        ),
    ]
