# Generated by Django 5.0.6 on 2024-07-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0005_alter_element_text_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='default_primary_dimensions',
            field=models.CharField(choices=[('1', 'Width'), ('2', 'Height')], default='1', max_length=255),
        ),
    ]
