# Generated by Django 5.0.6 on 2024-07-10 18:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulator', '0005_remove_element_type_remove_trainingdata_element_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('link', models.CharField(max_length=255)),
                ('max_width', models.FloatField(blank=True, null=True)),
                ('max_height', models.FloatField(blank=True, null=True)),
                ('vertical_mirror', models.BooleanField(default=False)),
                ('horizontal_mirror', models.BooleanField(default=False)),
                ('max_stitch_width', models.FloatField(blank=True, null=True)),
                ('max_stitch_height', models.FloatField(blank=True, null=True)),
                ('text_position', models.PositiveIntegerField(choices=[(1, 'BOTTOM'), (2, 'RIGHT'), (3, 'LEFT'), (4, 'CENTER'), (5, 'TOP')])),
                ('is_superimposed', models.BooleanField(default=False)),
                ('primary_dimensions', models.CharField(choices=[(1, 'Width'), (2, 'Height')], default=1, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text_id', models.CharField(max_length=10)),
                ('default_primary_dimensions', models.CharField(choices=[(1, 'Width'), (2, 'Height')], default=1, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_width', models.IntegerField()),
                ('container_height', models.IntegerField()),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='simulator.element')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='simulator.element')),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.type'),
        ),
    ]
