# Generated by Django 5.0.6 on 2024-07-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='default_primary_dimensions',
            field=models.PositiveIntegerField(choices=[(1, 'Width'), (2, 'Height')], default=1, max_length=50),
        ),
    ]
