# Generated by Django 5.0.6 on 2024-07-10 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_site', '0009_alter_contact_subject_alter_order_discount_and_more'),
        ('simulator', '0008_alter_type_default_primary_dimensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingdata',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marketing_site.product'),
        ),
    ]
