# Generated by Django 5.0.6 on 2024-07-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0009_alter_trainingdata_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='height',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='element',
            name='width',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
