# Generated by Django 5.0.6 on 2024-07-08 18:08

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing_site', '0008_alter_contact_subject_alter_order_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[(1, 'חיוב'), (2, 'זיכוי'), (3, 'תשלום')], default=1, max_length=50)),
                ('quantity', models.PositiveIntegerField(blank=True, default=1)),
                ('price', models.FloatField()),
                ('discount_percentage', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('comments', models.TextField(max_length=255)),
                ('date', models.DateField(default=datetime.datetime(2024, 7, 8, 21, 8, 19, 190202))),
                ('payment_method', models.CharField(choices=[(1, 'מזומן'), (2, 'כרטיס אשראי'), (3, 'העברה בנקאית'), (4, "צ'ק")], default=1, max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='marketing_site.order')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.customer')),
            ],
        ),
    ]
