# Generated by Django 5.0.6 on 2024-07-10 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 10, 21, 45, 25, 411094)),
        ),
    ]
