# Generated by Django 5.0.6 on 2024-06-19 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_site', '0001_initial'),
        ('shared_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared_models.customer'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='DEFAULT', max_length=255),
            preserve_default=False,
        ),
    ]
