# Generated by Django 5.0.6 on 2024-06-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_site', '0002_order_customer_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'פתוחה'), (2, 'סגורה')], default=1),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.PositiveIntegerField(choices=[(1, 'פרוכות'), (2, 'ספרי תורה'), (3, 'בימה'), (4, 'אחר')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'טיוטא'), (2, 'סגורה'), (3, 'שולמה')], default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.PositiveIntegerField(choices=[(1, 'פרוכות'), (2, 'ספרי תורה'), (3, 'בימה'), (4, 'שונות')]),
        ),
    ]
