# Generated by Django 5.0.6 on 2024-06-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_site', '0003_alter_contact_status_alter_contact_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_percentage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
