# Generated by Django 5.0.6 on 2024-07-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_site', '0004_alter_order_discount_alter_order_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.PositiveIntegerField(choices=[('1', 'פרוכות'), ('2', 'ספרי תורה'), ('3', 'בימה'), ('4', 'שונות')]),
        ),
    ]
