# Generated by Django 5.0.6 on 2024-07-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_site', '0004_alter_contact_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='WebAppUser',
        ),
    ]
