# Generated by Django 5.0.6 on 2024-07-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_site', '0006_alter_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.PositiveIntegerField(choices=[(1, 'פרוכות'), (2, 'ספרי תורה'), (2, 'בימה'), (4, 'שונות')]),
        ),
    ]
