# Generated by Django 5.0.6 on 2024-07-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_site', '0006_webappuser_groups_webappuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webappuser',
            name='otp_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webappuser',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
