# Generated by Django 5.0.6 on 2024-08-08 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_site', '0007_webappuser_otp_code_webappuser_otp_expires_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='link',
            new_name='url',
        ),
    ]
