# Generated by Django 5.0.6 on 2024-07-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_site', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.PositiveIntegerField(choices=[(1, 'פרוכות'), (2, 'ספרי תורה'), (3, 'בימה'), (4, 'אחר')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_percentage',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.PositiveIntegerField(choices=[(1, 'פרוכות'), (2, 'ספרי תורה'), (3, 'בימה'), (4, 'שונות')]),
        ),
    ]
