# Generated by Django 5.0.6 on 2024-07-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_site', '0008_alter_contact_subject_alter_order_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[(1, 'פרוכות'), (2, 'ספרי תורה'), (3, 'בימה'), (4, 'אחר')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_percentage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.PositiveIntegerField(choices=[(1, 'פרוכות'), (2, 'ספרי תורה'), (2, 'בימה'), (4, 'שונות')]),
        ),
    ]
