# Generated by Django 5.0.6 on 2024-08-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_site', '0008_rename_link_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='local_link',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
